### ISSUE TITLE
List Collection helper methods.

### ISSUE THREAD

**Issue by mik3hall** [blockchain/api-v1-client-java#14]
Another enhancement request.
In debugging my code I was having trouble figuring out what script the public key I was hashing was supposed to match up with.
I added this...
    				List<Transaction> trans = addr160.getTransactions();
    				System.out.println("tran is for this addr is " + trans.contains(txCurrent));
    				System.out.println("prior is for this addr is " + trans.contains(txLast));
Default this did not work. The results of the contains method returned false.
I subclassed Transaction adding...

	public boolean equals(Object o) {
		if (o == null) return false;
		if (o instanceof Transaction) {
			Transaction that = (Transaction)o;
			return (this.getHash().equals(that.getHash()));
		}
		return false;
	}
	
	public int hashCode() {
		return getHash().hashCode();
	}

The contains method then worked. (Telling me my address was true/valid for both the current and prior transactions. Not a lot of help in deciding which had my script of interest but at least I knew the address did map to the transactions somewhere).

You could very possibly think of a better way to implement these methods.
You might consider whether other classes you return as List collections should include something similar as well.

Thanks.

**Comment by matsjj** [comment]
Acknowledged, all relevant objects missed an equal(..)/hashCode(..) method, which made life difficult for a lot of developers. I just implemented them, thank you for your feedback! :)

**Comment by mik3hall** [comment]
> On Oct 21, 2015, at 2:04 AM, matsjj <notifications@github.com> wrote:
> 
> Acknowledged, all relevant objects missed an equal(..)/hashCode(..) method, which made life difficult for a lot of developers. I just implemented them, thank you for your feedback! :)
> 


Thank you.

Michael Hall
