### ISSUE TITLE
Add maven repository to gradle

### ISSUE THREAD

**Issue by Kostronor** [blockchain/api-v1-client-java#18]
I am having issues including your API into my project.

Using this code gives me no resolved dependencies:

```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://raw.githubusercontent.com/blockchain/api-v1-client-java/mvn-repo/"
        }
    }
}

dependencies {
    compile("info.blockchain:api:v1.0.3")
}
```

**Comment by medved30135** [comment]
<repository>
        <id>api-v1-client-java-mvn-repo</id>
        <url>https://raw.githubusercontent.com/blockchain/api-v1-client-java/mvn-repo/</url>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
        </snapshots>
    </repository>

**Comment by medved30135** [comment]
<dependency>
    <groupId>info.blockchain</groupId>
    <artifactId>api</artifactId>
    <version>LATEST</version>
  </dependency>

**Comment by Kostronor** [comment]
`compile 'info.blockchain:api:LATEST'` not working

![image](https://cloud.githubusercontent.com/assets/644950/11324153/e31db0f2-9129-11e5-873c-7edc4a7b414a.png)

As you see here

**Comment by mpfluger** [comment]
I just fixed this. You need to make one small change: instead of `compile("info.blockchain:api:v1.0.3")`, it's `compile("info.blockchain:api:1.0.3")`.
