### ISSUE TITLE
info.blockchain.api.blockexplorer.BlockExplorer.java

### ISSUE THREAD

**Issue by ecerchia** [blockchain/api-v1-client-java#20]
- Maybe would be useful to add a wiki to our definition of UNIX time
https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/blockexplorer/BlockExplorer.java#L211. Also we need extra care with getting the time from the server as it might be setup for different timezones and the server's code should be able to detect this and make the necessary transformations.
- Maybe we could rename to getBlocksMinedToday()? https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/blockexplorer/BlockExplorer.java#L204. Could be useful for command line wizards for which method documentation doesn't appear as easily as in an IDE.
- Duplicate code for param construction https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/blockexplorer/BlockExplorer.java#L181, would extract in several functions that return different variations w/ ("format", "json"), ("api_code", apiCode), ("active", address) pairs
- Would have a long try {} that includes all the statements https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/blockexplorer/BlockExplorer.java#L139 so that we separate the normal happy path of execution from the exception handling. I think is cleaner like this. Ex of exception handling code https://github.com/blockchain/service-receive-v2/blob/master/src/main/java/info/blockchain/api/dao/BlockLogDao.java#L33
- Would loose the coupling here https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/blockexplorer/BlockExplorer.java#L53. This class knows too much about the internals of HttpClient. I'd rather create distinct methods in HttpClient like getRawRx(txHash, apiCode), getRawBlock(blockHash, apiCode) and let it build its own URIs since this is HttpClient's responsibility.

**Comment by pdpi** [comment]
> I'd rather create distinct methods in HttpClient like getRawRx(txHash, apiCode), getRawBlock(blockHash, apiCode) and let it build its own URIs since this is HttpClient's responsibility.

I agree that this is a bit awkward right now, I disagree with that approach. That would make for the reverse problem — HttpClient would stop being an HTTP Client and become quite tightly coupled with our API.

**Comment by ecerchia** [comment]
info.blockchain.api.blockexplorer.HttpClient class in our own package has all the rights to know stuff about our API since it lives in our package and we can control and change it the way we need. Probably the name doesn't help with emphasizing this. Would rename it to smth more suggestive like BlockchainHttpClient. HttpClient needs to be coupled to smth to perform useful work so the question is where does it make more sense to do the coupling. The first steps toward coupling it to our APIs has already been made https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/HttpClient.java#L16

**Comment by pdpi** [comment]
The `BlockExplorer.getRawBlock(blockHash, apiCode)` precisely what you're describing, except namespaced into a BlockExplorer class.

The problem here is usage: we should have  `get("rawtx", argumentsMap)` instead of `get("rawtx/" + txHash + "?api_code=" + apiCode, null)` — instead, we're sidestepping the argument handling in the implementation of `get` with all the potential issues that entails.
