### ISSUE TITLE
info.blockchain.api.wallet.Wallet

### ISSUE THREAD

**Issue by pdpi** [blockchain/api-v1-client-java#27]
* Pretty sure [these negations](https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/wallet/Wallet.java#L62) all cancel out. At any rate, that statement is somewhat awkward and can almost certainly be simplified.
* We should guard against `recipients` having a null key around [here](https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/wallet/Wallet.java#L110).

**Comment by ecerchia** [comment]
Added few more comments here https://github.com/blockchain/api-v1-client-java/issues/30

**Comment by mpfluger** [comment]
Fixed in 5ecafe2bde658863056344dd7170ee2885e7f36f

**Comment by mpfluger** [comment]
I undid my change to Wallet.java - it seems like there is generally no checking done on parameters, this is all left to the server. The same is true for `recipients.put(null, 1)` - JSON serialization will work, the server won't accept it.
