### ISSUE TITLE
info.blockchain.api.etc.Base58.java

### ISSUE THREAD

**Issue by ecerchia** [blockchain/api-v1-client-java#28]
- Why did we add these comments to our source file https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/etc/Base58.java#L4?
- It feels like we need a directional map between the characters and their indexes, this problem was already solved by Apache with BidiMap class http://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/BidiMap.html, this would make this code disappear https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/etc/Base58.java#L51

**Comment by pdpi** [comment]
Current implementation is O(1) on lookups, which the BidiMaps can't guarantee.
