### ISSUE TITLE
java/info/blockchain/api/wallet/Wallet.java class

### ISSUE THREAD

**Issue by ecerchia** [blockchain/api-v1-client-java#30]
- we are retrieving the first value in the sender.https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/wallet/Wallet.java#L105 What if there are more values?
- else also means size = 0. Is this ok? https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/wallet/Wallet.java#L108
- line too long and 'a' renaming https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/wallet/Wallet.java#L161

**Comment by matsjj** [comment]
- By definition of the if branch, there is only one receiver, so just grabbing the first one should be okay.

- Good call, we should probably add Preconditions to most of these calls

**Comment by ecerchia** [comment]
Great, added Guava dependency in order to use the Preconditions class https://github.com/blockchain/api-v1-client-java/commit/1fb2c4cbfedcbc678aff528e5cd60fd6c560ffd5
