### ISSUE TITLE
Please return String or Long Satoshis instead of Double

### ISSUE THREAD

**Issue by andychase** [blockchain/api-v1-client-java#6]
This is the same issue as reported before: #5

Specifically I'm referring to this (for my use): [ExchangeRates.java Line 104](https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/exchangerates/ExchangeRates.java#L104) but the use of double is rampant throughout the source.

You said previously that the api is using a double and you simply are mirroring this. This is incorrect. The server api is returning a **String**, but you parse it into a double.

* https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

**Comment by matsjj** [comment]
Indeed, the use of double in this context is strongly discouraged. I changed all critical instances with BigDecimal. It might not make much of a difference some cases, but it encourages other developers to actually use BigDecimal where necessary when they build new things on top of our API.
