### ISSUE TITLE
Transaction via Address is always blockheight -1 and not a double spend

### ISSUE THREAD

**Issue by AmazingDreams** [blockchain/api-v1-client-java#8]
See here:

https://github.com/blockchain/api-v1-client-java/blob/master/src/main/java/info/blockchain/api/blockexplorer/Address.java#L46

The data is available though, e.g: https://blockchain.info/nl/rawaddr/17eD8wZYxXNGFW7VF24M4i8z4bn2XuLhBF

**Comment by matsjj** [comment]
Thanks, fixed it.
