### ISSUE TITLE
enable custom HTTP client

### ISSUE THREAD

**Issue by ewot** [blockchain/api-v1-client-java#9]
The class documentation in the HTTPClient states that is possible to override the get and post methods. As they are static this is not possible.

I propose a refactoring making HTTPClient an interface without static methods and then making it possible to inject the client in the services.

**Comment by matsjj** [comment]
Don't know if this is still a demand for that, but I made a compromise towards being able to set a global custom HttpClient for use in the services. If you want to implement your own HttpClient, implement HttpClientInterface and set it with HttpClient.setCustomHttpClient(...).
